/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Comments;
import static Lib.LoginPreferences.loadId;
import Classes.Posts;
import Classes.Sharing;
import Classes.Users;
import Config.Connect;
import static Lib.Func.timeAgo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER NITRO
 */
public class Post extends javax.swing.JFrame {

    /**
     * Creates new form SINGLE_POST
     */
    int id;
    int user_id = loadId();
    int post_user_id;
//  for comment
    int offset = 0;
    int limit = 10;
    int total_comment = 0;
    public Post(int id) {

        
        this.id = id;
        
        initComponents();
        panelComment.setLayout(new BoxLayout(panelComment, BoxLayout.Y_AXIS));
        updateComment(offset, limit);
        
        Posts post = new Posts(id);
        total_comment = post.totalComment();
        if(post.getType() == 'S'){
            post = new Sharing(id);
            if(post.getComment() == 0){
                formComment.setVisible(false);
            }
        }
        
        title.setText(post.getTitle());
        Users userPost = new Users(post.getUserId());
        postedBy.setText("Posted " + timeAgo(Long.valueOf(userPost.getDate())) + " by " + userPost.getName());
        post_user_id = userPost.getId();
        content.setText("<html>" + post.getContent().replace("\n", "<br>")+ "</html>");
        if(post.getComment() == 0){
            comments.setText("Komentar Dinonaktifkan!");
            panelComment.removeAll();
            panelComment.revalidate();
            panelComment.repaint();
        }else{
            comments.setText(total_comment + " Comments");
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void updateComment(int offset, int limit){
         try (Connection conn = Connect.getConnection(); Statement stmt = conn.createStatement()) {
            String query = "SELECT * FROM comments WHERE post_id = " + id + " ORDER BY id DESC LIMIT " + offset + "," + limit;
            ResultSet rs = stmt.executeQuery(query);
            int total = 0;
            while (rs.next()) {
                this.offset++;
                Comments comment = new Comments(rs.getInt("id")); 
                CardComment cm = new CardComment(comment);
                panelComment.add(cm);
            }
            String query_total = "SELECT COUNT(*) FROM comments WHERE post_id = " + id + " ORDER BY id DESC";
            ResultSet rs_total = stmt.executeQuery(query_total);
            while (rs_total.next()) {
                total = rs_total.getInt(1);
            }
            if(offset < total){
                buttonMore();
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
         
    }
    
    private void buttonMore(){
        JButton buttonMore = new JButton();
        buttonMore.setSize(400,400);
        buttonMore.setVisible(true);
        buttonMore.setText("See More");
        buttonMore.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                panelComment.remove(buttonMore);
                panelComment.revalidate();
                panelComment.repaint();
                updateComment(offset,limit);
            }
        });
        panelComment.add(buttonMore);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        comments = new javax.swing.JLabel();
        formComment = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnSend = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComment = new javax.swing.JTextArea();
        title = new javax.swing.JLabel();
        postedBy = new javax.swing.JLabel();
        content = new javax.swing.JLabel();
        panelComment = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        comments.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        comments.setText("JUMLAH COMMENT");

        formComment.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 16)); // NOI18N
        jLabel4.setText("Comment");

        btnSend.setBackground(new java.awt.Color(22, 50, 91));
        btnSend.setText("SEND");
        btnSend.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        txtComment.setColumns(20);
        txtComment.setRows(5);
        txtComment.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(22, 50, 91)));
        jScrollPane2.setViewportView(txtComment);

        javax.swing.GroupLayout formCommentLayout = new javax.swing.GroupLayout(formComment);
        formComment.setLayout(formCommentLayout);
        formCommentLayout.setHorizontalGroup(
            formCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formCommentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        formCommentLayout.setVerticalGroup(
            formCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formCommentLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        title.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        title.setText("JUDUL");

        postedBy.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        postedBy.setText("Diposting oleh");
        postedBy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postedByMouseClicked(evt);
            }
        });

        content.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        content.setText("CONTENT");

        panelComment.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelCommentLayout = new javax.swing.GroupLayout(panelComment);
        panelComment.setLayout(panelCommentLayout);
        panelCommentLayout.setHorizontalGroup(
            panelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelCommentLayout.setVerticalGroup(
            panelCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 294, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelComment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(formComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(comments))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(title)
                                    .addComponent(postedBy)
                                    .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postedBy)
                .addGap(12, 12, 12)
                .addComponent(content)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comments)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 620));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        if("".equals(txtComment.getText())){
            JOptionPane.showMessageDialog(null,
            "Form harus terisi!",
            "Warning",
            JOptionPane.WARNING_MESSAGE);
            return;
        }
        try (Connection conn = Connect.getConnection(); Statement stmt = conn.createStatement()) {
            String insertUser = "INSERT INTO comments (user_id, post_id, content, date) VALUES(" +
                  user_id  + "," + id + ",'" + txtComment.getText() + "','" + System.currentTimeMillis() + "')";
            int i = stmt.executeUpdate(insertUser);
            if (i > 0) {
//                JOptionPane.showMessageDialog(null,
//                "Komentar berhasil ditambahkan!");
                txtComment.setText("");
                panelComment.removeAll();
                panelComment.revalidate();
                panelComment.repaint();
                updateComment(0,offset+1);
                offset = 3;
                total_comment++;
                comments.setText(total_comment + " Comments");
            } else {
                JOptionPane.showMessageDialog(null,
                "Komentar gagal ditambahkan!!");
            }

        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void postedByMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postedByMouseClicked
        // TODO add your handling code here:
        Profile profile = new Profile(post_user_id);
        profile.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        profile.setVisible(true);
    }//GEN-LAST:event_postedByMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Post.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Post(2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle btnSend;
    private javax.swing.JLabel comments;
    private javax.swing.JLabel content;
    private javax.swing.JPanel formComment;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelComment;
    private javax.swing.JLabel postedBy;
    private javax.swing.JLabel title;
    private javax.swing.JTextArea txtComment;
    // End of variables declaration//GEN-END:variables
}
